name = "file-transfer-app"
main = "src/index.ts"
compatibility_date = "2022-06-30"
type = "webpack"

account_id = "6b649749fcfa08038b3888bb3b4d7de6"
workers_dev = true

binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'file-transfer-app' 
